P1207_EX/P1207_EX/Models/ErrorViewModel.cs
using System;

namespace P1207_EX.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

P1207_EX/P1207_EX/Models/SponsorModel.cs
using System;
using System.ComponentModel;

namespace P1207_EX.Models
{
    public class SponsorModel
    {
        [DisplayName("Sponsor Id: ")]
        public int Id { get; set; }
        [DisplayName("First Name: ")]
        public string FirstName { get; set; }
        [DisplayName("Surname: ")]
        public string Surname { get; set; }
        [DisplayName("Sponsored Money: ")]
        public int Amount { get; set; }
        [DisplayName("Sponsored Animal Id: ")]
        public int AnimalId { get; set; }
    }
}

P1207_EX/P1207_EX/Models/TodoItemsListModel.cs
using System.Collections.Generic;

namespace P1207_EX.Models
{
    public class TodoItemsListModel
    {
        public List<TodoModel> Todos { get; set; }
    }
}

P1207_EX/P1207_EX/Models/TodoModel.cs
using System.ComponentModel;

namespace P1207_EX.Models
{
    public class TodoModel
    {
        [DisplayName("List Name: ")]
        public string Name { get; set; }
        [DisplayName("Description: ")]
        public string Description { get; set; }
    }
}

P1207_EX/P1207_EX/Models/ZooModel.cs
using System.ComponentModel;

namespace P1207_EX.Models
{
    public class ZooModel
    {
        [DisplayName("Animal Id: ")]
        public int Id { get; set; }
        [DisplayName("Animal Name: ")]
        public string Name { get; set; }
        [DisplayName("Description: ")]
        public string Description { get; set; }
        [DisplayName("Age: ")]
        public int Age { get; set; }
        [DisplayName("Gender: ")]
        public string Gender { get; set; }
    }
}

P1207_EX/P1207_EX/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using P1207_EX.Models;
using P1207_EX.Services;
using System.Diagnostics;

namespace P1207_EX.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataService _dataService;
        private readonly string _jsonFile = "data.json";

        public HomeController(DataService dataService)
        {
            _dataService = dataService;
        }

        public IActionResult TodoItemsList()
        {
            var todosList = new TodoItemsListModel()
            {
                Todos = _dataService.GetAll()
            };
            return View(todosList);
        }

        public IActionResult DisplaySubmitData()
        {
            var emptyModel = new TodoModel();
            return View(emptyModel);
        }
        
        public IActionResult SendSubmitData(TodoModel model)
        {
            _dataService.Add(model);
            return RedirectToAction("DisplaySubmitData");
        }

        public IActionResult DisplaySubmitDataToFile()
        {
            var emptyModel = new TodoModel();
            return View(emptyModel);
        }

        public IActionResult SendSubmitDataToFile(TodoModel model)
        {
            _dataService.WriteToJson(_jsonFile, model);
            return RedirectToAction("DisplaySubmitDataToFile");
        }

        public IActionResult ToDoItemsListFromFile()
        {
            return View(_dataService.GetAllJson(_jsonFile));
        }

        public IActionResult DeleteListItem(TodoModel model)
        {
            _dataService.DeleteFromJson(_jsonFile, model);
            return RedirectToAction("ToDoItemsListFromFile");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

P1207_EX/P1207_EX/Controllers/SponsorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using P1207_EX.Models;
using P1207_EX.Services;

namespace P1207_EX.Controllers
{
    public class SponsorController : Controller
    {
        private readonly SponsorService _sponsorService;
        public SponsorController(SponsorService sponsorService)
        {
            _sponsorService = sponsorService;
        }

        public IActionResult Sponsors()
        {
            return View(_sponsorService.GetAll());
        }

        public IActionResult DisplayAddSponsor()
        {
            return View(new SponsorModel());
        }

        public IActionResult SubmitAddNewSponsor(SponsorModel sponsor)
        {
            _sponsorService.AddNew(sponsor);
            return RedirectToAction("Sponsors");
        }

        public IActionResult DisplayUpdateSponsor(SponsorModel sponsor)
        {
            return View(sponsor);
        }

        public IActionResult SubmitUpdate(SponsorModel sponsor)
        {
            try
            {
                _sponsorService.Update(sponsor);
                return RedirectToAction("Sponsors");
            }
            catch
            {
                return RedirectToAction("DisplayUpdateSponsor", sponsor);
            }
        }
    }
}

P1207_EX/P1207_EX/Controllers/ZooController.cs
using Microsoft.AspNetCore.Mvc;
using P1207_EX.Models;
using P1207_EX.Services;

namespace P1207_EX.Controllers
{
    public class ZooController : Controller
    {
        private readonly ZooService _zooService;
        public ZooController(ZooService zooService)
        {
            _zooService = zooService;
        }
        // GET: ZooController1
        public ActionResult Index()
        {
            return View(_zooService.GetAll());
        }

        public IActionResult DisplayAddNewAnimal()
        {
            var empty = new ZooModel();
            return View(empty);
        }

        public IActionResult SubmitNewAnimal(ZooModel model)
        {
            _zooService.AddNewAnimal(model);
            return RedirectToAction("DisplayAddNewAnimal");
        }

        public IActionResult DeleteAnimal(ZooModel model)
        {
            _zooService.DeleteAnimal(model);
            return RedirectToAction("Index");
        }

        public IActionResult DisplayUpdateAnimal(ZooModel model)
        {
            return View(model);
        }

        public IActionResult SubmitUpdate(ZooModel model)
        {
            _zooService.UpdateAnimal(model);
            return RedirectToAction("Index");
        }
    }
}

P1207_EX/P1207_EX/Views/Home/DisplaySubmitData.cshtml
@model TodoModel

@using (Html.BeginForm("SendSubmitData", "Home", FormMethod.Post))
{
    @Html.LabelFor(a => a.Name)
    @Html.TextBoxFor(a => a.Name)

    @Html.LabelFor(a => a.Description)
    @Html.TextBoxFor(a => a.Description)
        
    <input type="submit" value="Submit"/>
}

P1207_EX/P1207_EX/Views/Home/DisplaySubmitDataToFile.cshtml
@model TodoModel

@using (Html.BeginForm("SendSubmitDataToFile", "Home", FormMethod.Post))
{
    @Html.LabelFor(a => a.Name)
    @Html.TextBoxFor(a => a.Name)

    @Html.LabelFor(a => a.Description)
    @Html.TextBoxFor(a => a.Description)
        
    <input type="submit" value="Submit"/>
}

P1207_EX/P1207_EX/Views/Home/ToDoItemsListFromFile.cshtml
@model List<TodoModel>

<ul>
    @foreach(var todo in @Model)
    {
        <li>@todo.Name - @todo.Description @Html.ActionLink("X", "DeleteListItem", "Home", todo)</li>
    }
</ul>

P1207_EX/P1207_EX/Views/Home/TodoItemsList.cshtml
@model TodoItemsListModel

<ul>
    @foreach(var todo in @Model.Todos)
    {
        <li>@todo.Name - @todo.Description</li>
    }
</ul>

P1207_EX/P1207_EX/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - P1207_EX</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="TodoItemsList">P1207_EX</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="TodoItemsList">Todo Items List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="DisplaySubmitData">Add new Todo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ToDoItemsListFromFile">Todo Items List (F)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SendSubmitDataToFile">Add new Todo (F)</a>
                        </li>
                        <div class="dropdown">
                          <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Zoo(DB)
                          </button>
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-area="" asp-controller="Zoo" asp-action="Index">List all Animals</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Zoo" asp-action="DisplayAddNewAnimal">Add new animal</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Sponsor" asp-action="Sponsors">View all sponsors</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Sponsor" asp-action="DisplayAddSponsor">Add new sponsor</a>
                          </div>
                        </div>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - P1207_EX - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

P1207_EX/P1207_EX/Views/Sponsor/DisplayAddSponsor.cshtml
@model SponsorModel

@using (Html.BeginForm("SubmitAddNewSponsor", "Sponsor", FormMethod.Post))
{
    @Html.LabelFor(s => s.FirstName)
    @Html.TextBoxFor(s => s.FirstName) 
    <br />
    @Html.LabelFor(s => s.Surname)
    @Html.TextBoxFor(s => s.Surname)
    <br />
    @Html.LabelFor(s => s.Amount)
    @Html.TextBoxFor(s => s.Amount, new {@type = "number"})
    <br />
    @Html.LabelFor(s => s.AnimalId)
    @Html.TextBoxFor(s => s.AnimalId, new {@type = "number"})
    <br />
    <input type = "submit" value = "submit" />
}

P1207_EX/P1207_EX/Views/Sponsor/DisplayUpdateSponsor.cshtml
@model SponsorModel

@using (Html.BeginForm("SubmitUpdate", "Sponsor", FormMethod.Post))
{
    @Html.TextBoxFor(s => s.Id, new {@readonly = "readonly"})

    @Html.TextBoxFor(s => s.FirstName)

    @Html.TextBoxFor(s => s.Surname)

    @Html.TextBoxFor(s => s.Amount, new {@type = "number"})

    @Html.TextBoxFor(s => s.AnimalId, new {@type = "number"})
        
    <input type="submit" value="Update"/>
}

P1207_EX/P1207_EX/Views/Sponsor/Sponsors.cshtml
@model List<SponsorModel>

<h2>All our sponsors and potential sponsors.</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Surname</th>
        <th>Amount</th>
        <th>Sponsored Animal Id</th>
        <th>Action</th>
    </tr>
    @foreach(var sponsor in @Model)
    {
        <tr>
            <td>@sponsor.Id</td>
            <td>@sponsor.FirstName</td>
            <td>@sponsor.Surname</td>
            <td>@sponsor.Amount</td>
            <td>@sponsor.AnimalId</td>
            <td>@Html.ActionLink("X", "DeleteSponsor", "Sponsor", sponsor) @Html.ActionLink("Update", "DisplayUpdateSponsor", "Sponsor", sponsor)</td>
        </tr>
    } 
</table>

P1207_EX/P1207_EX/Views/Zoo/DisplayAddNewAnimal.cshtml
@model ZooModel

@using (Html.BeginForm("SubmitNewAnimal", "Zoo", FormMethod.Post))
{
    @Html.LabelFor(a => a.Name)
    @Html.TextBoxFor(a => a.Name)

    @Html.LabelFor(a => a.Description)
    @Html.TextBoxFor(a => a.Description)

    @Html.LabelFor(a => a.Age)
    @Html.TextBoxFor(a => a.Age, new {@type = "number"})
    
    @Html.LabelFor(a => a.Gender)
    @Html.TextBoxFor(a => a.Gender)

    <input type = "submit" value = "submit" />
}

P1207_EX/P1207_EX/Views/Zoo/DisplayUpdateAnimal.cshtml
@model ZooModel

@using (Html.BeginForm("SubmitUpdate", "Zoo", FormMethod.Post))
{
    @Html.TextBoxFor(a => a.Id, new {@readonly = "readonly"})

    @Html.TextBoxFor(a => a.Name)

    @Html.TextBoxFor(a => a.Description)

    @Html.TextBoxFor(a => a.Age, new {@type = "number"})

    @Html.TextBoxFor(a => a.Gender)
        
    <input type="submit" value="Update"/>
}

P1207_EX/P1207_EX/Views/Zoo/Index.cshtml
@model List<ZooModel>
<h2>All animals in the zoo</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Description</th>
        <th>Age</th>
        <th>Gender</th>
        <th>Action</th>
    </tr>
    @foreach(var animal in @Model)
    {
        <tr>
            <td>@animal.Id</td>
            <td>@animal.Name</td>
            <td>@animal.Description</td>
            <td>@animal.Age</td>
            <td>@animal.Gender</td>
            <td>@Html.ActionLink("X", "DeleteAnimal", "Zoo", animal) @Html.ActionLink("Update", "DisplayUpdateAnimal", "Zoo", animal)</td>
        </tr>
    }
</table>